// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get usernameLabel => 'Username';

  @override
  String get usernameHint => 'Username';

  @override
  String get max20Characters => 'Maximum 20 characters';

  @override
  String get disclaimer =>
      'The values provided by this application are approximate estimates and should not be interpreted as professional or technical advice, nor used as the sole basis for important decisions. This tool does not replace certified measuring instruments or the judgment of a qualified professional.\n\nAlthough it has been developed with the utmost care, no guarantee is given regarding the accuracy, completeness, or suitability of the results under all circumstances. The interpretation and use of the information collected are the sole responsibility of the user.\n\nThe development team shall not, under any circumstances, assume any liability for direct or indirect damages that may arise from the use, misuse, or interpretation of the data generated by the application.\n\nUse of this app implies express acceptance of these terms.';

  @override
  String get disclaimerMustBeAccepted =>
      'You must accept the disclaimer to continue';

  @override
  String get disclaimerAcceptance => 'I accept the disclaimer';

  @override
  String get disclaimerScrollContinue => 'Keep scrolling to continue';

  @override
  String get disclaimerReadingText => 'Keep reading to continue';

  @override
  String get startProfile => 'Start profile';

  @override
  String get importProfile => 'Import profile';

  @override
  String get createProfile => 'Create profile';

  @override
  String get loginTitle => 'Log\nIn';

  @override
  String get registerTitle => 'Register';

  @override
  String get userAlreadyRegistered => 'User already registered with this email';

  @override
  String get userNotFound => 'User not found';

  @override
  String get profileMenuItem => 'User profile';

  @override
  String get creditsMenuItem => 'Credits';

  @override
  String get creditsMenuDescription =>
      'This application has been developed to facilitate fruit diameter measurement through photography. It allows different types of measurements to be taken quickly and accurately, helping to improve quality control and decision-making in agricultural, commercial, or research processes.';

  @override
  String get creditsDevelopedBy => 'Developed by';

  @override
  String get creditsProjectAcknowledgments =>
      'Project acknowledgments: [Text to complete]';

  @override
  String get creditsFundingAcknowledgments =>
      'Funding entities acknowledgments: [Text to complete]';

  @override
  String get creditsDevelopmentText =>
      'FruitMeasureApp has been developed by the Universitat de Lleida (UdL) and the Institut de Recerca i Tecnologia Agroalimentàries (IRTA) within the framework of the demonstrative activity \"FruitMeasureApp: Validation and prototyping of an AI-based mobile application to measure fruit in the field\" (Activity co-financed by the EU through the intervention 7201 of the Strategic Plan of the CAP 2023-2027).';

  @override
  String creditsWebsiteText(String url) {
    return 'Complementary resources related to FruitMeasureApp are available on website $url.';
  }

  @override
  String get creditsWebsiteUrl => 'https://fruitmeasureapp.udl.cat/';

  @override
  String get logoutMenuItem => 'Log out';

  @override
  String get logoutDialogTitle => 'Confirm';

  @override
  String get logoutDialogMessage => 'Are you sure you want to log out?';

  @override
  String get cancel => 'Cancel';

  @override
  String get profileTitle => 'Profile';

  @override
  String get nameLabel => 'Name';

  @override
  String get emailLabel => 'Email';

  @override
  String get emailRecommended =>
      'Email is not mandatory but recommended for sharing data';

  @override
  String get optionsLabel => 'Options';

  @override
  String get deletePhotosOption => 'Delete images from device';

  @override
  String get editProfile => 'Edit profile';

  @override
  String get exportProfile => 'Export profile';

  @override
  String get switchProfile => 'Switch user';

  @override
  String get deleteProfile => 'Delete profile';

  @override
  String get confirmDeleteProfileTitle => 'Delete profile';

  @override
  String get confirmDeleteProfileMessage =>
      'Are you sure you want to delete this user? All stored data will be lost.';

  @override
  String get confirm => 'Confirm';

  @override
  String get confirmChangesTitle => 'Confirm changes';

  @override
  String get confirmChangesMessage =>
      'Are you sure you want to confirm the changes made?';

  @override
  String get saveChanges => 'Save changes';

  @override
  String get actionDone => 'Action completed successfully';

  @override
  String get actionNotDone => 'The action could not be completed';

  @override
  String get createPlot => 'Create plot';

  @override
  String get editPlot => 'Edit plot';

  @override
  String get deletePlot => 'Delete plot';

  @override
  String get confirmDeleteElementTitle => 'Delete element';

  @override
  String get confirmDeleteElementMessage =>
      'Are you sure you want to permanently delete this element?';

  @override
  String get mapTypeTooltip => 'Map type';

  @override
  String get mapTypeNormal => 'Normal';

  @override
  String get mapTypeSatellite => 'Satellite';

  @override
  String get mapTypeHybrid => 'Hybrid';

  @override
  String get mapTypeTerrain => 'Terrain';

  @override
  String get goToMyLocationTooltip => 'My location';

  @override
  String get locationServicesDisabled => 'Location services are disabled.';

  @override
  String get locationPermissionDenied =>
      'Location permissions have been denied.';

  @override
  String get locationPermissionPermanentlyDenied =>
      'Location permissions are permanently denied. Please enable them in the app settings.';

  @override
  String get plotNameLabel => 'Plot name';

  @override
  String get plotNameHint => 'Plot name';

  @override
  String get farmerNameLabel => 'Farmer\'s name';

  @override
  String get farmerNameHint => 'Farmer\'s name';

  @override
  String get plantationDateLabel => 'Planting date';

  @override
  String get plantationDateHint => 'Planting date';

  @override
  String get varietyLabel => 'Specie and Variety';

  @override
  String get varietyHint => 'Specie and Variety';

  @override
  String get descriptionLabel => 'Description';

  @override
  String get descriptionHint => 'Description';

  @override
  String get plotLocationLabel => 'Plot location';

  @override
  String get locationDialogTitle => 'Location (WGS84)';

  @override
  String get tapToEditMap => 'Tap to edit';

  @override
  String get tapToViewMap => 'Tap to view map';

  @override
  String get createMeasurement => 'Create measurement';

  @override
  String get editMeasurement => 'Edit measurement';

  @override
  String get deleteMeasurement => 'Delete measurement';

  @override
  String get measurementModelLabel => 'Model';

  @override
  String get measurementModelHint => 'Model';

  @override
  String get measurementObservationsLabel => 'Observations';

  @override
  String get measurementObservationsHint => 'Observations';

  @override
  String get exitWithoutSave => 'Exit without saving';

  @override
  String get exitWithoutSaveQuestion =>
      'Are you sure you want to exit without saving?';

  @override
  String get accept => 'Accept';

  @override
  String get supportDistance => 'Camera support distance (mm)';

  @override
  String get users => 'Users';

  @override
  String get plotView => 'Plot view';

  @override
  String get plots => 'Plots';

  @override
  String get searchPlots => 'Search plot...';

  @override
  String get withoutPlots => 'No plots';

  @override
  String get noPlotsRegistered => 'No plots registered';

  @override
  String get copy => 'Copy';

  @override
  String get compareCurves => 'Compare curves';

  @override
  String get importPlots => 'Import plots';

  @override
  String get duplicatePlots => 'Duplicate plot';

  @override
  String get downloadKML => 'Download as KML';

  @override
  String get exportPlots => 'Export plots';

  @override
  String get dataMeasurement => 'Measurement data';

  @override
  String get caliber => 'Caliber';

  @override
  String get latitude => 'Latitude';

  @override
  String get longitude => 'Longitude';

  @override
  String get notAvalaible => 'Not available';

  @override
  String get delete => 'Delete';

  @override
  String get camera => 'Camera';

  @override
  String get gallery => 'Gallery';

  @override
  String get takeNewShot => 'Take new shot';

  @override
  String get editShot => 'Edit shot';

  @override
  String get detectionFruit => 'Fruit';

  @override
  String get statistics => 'Statistics';

  @override
  String get caliberSeasonText => 'Caliber - Season (thinning/ripening)';

  @override
  String get withoutData => 'No data';

  @override
  String get caliberMin => 'Minimum caliber';

  @override
  String get caliberAvg => 'Average caliber';

  @override
  String get caliberMax => 'Maximum caliber';

  @override
  String get numberOfImages => 'No. of images';

  @override
  String get avgFruitsPerImage => 'Fruits/image';

  @override
  String get shareChartImage => 'Share as image';

  @override
  String get shareChartCsv => 'Share as CSV';

  @override
  String get modelUpdateTo => 'Model updated to';

  @override
  String get noImageCaptured => 'No captures';

  @override
  String get noCaptureForMeasurement =>
      'No captures found for this measurement';

  @override
  String get makeCapture => 'Take capture';

  @override
  String get selectImageFromGallery => 'Select image from gallery';

  @override
  String get loadingProcessingImage => 'Processing image...';

  @override
  String get selectingImages => 'Selecting images...';

  @override
  String get comparative => 'Comparative';

  @override
  String get growthCurve => 'Growth curve';

  @override
  String get compareGrowthCurves => 'Compare growth curves';

  @override
  String get currentGrowthRate => 'Current growth rate';

  @override
  String get millimetersDay => 'mm/day';

  @override
  String get temporalEvolutionPlot =>
      'Temporal evolution of the plot (caliber)';

  @override
  String get tapPointsForDetails => 'Tap points for details';

  @override
  String get calendar => 'Calendar';

  @override
  String get withoutObservations => 'No observations';

  @override
  String get measurementLabel => 'Measurement';

  @override
  String get selectModelLabel => 'Select a model';

  @override
  String get creationDateLabel => 'Creation date';

  @override
  String get measurementsLabel => 'Measurements';

  @override
  String get searchMeasurement => 'Search measurement...';

  @override
  String get withoutMeasurements => 'No measurements';

  @override
  String get noMeasurementsRegistered => 'No measurements registered';

  @override
  String get exportMeasurements => 'Export measurements';

  @override
  String get importMeasurements => 'Import measurements';

  @override
  String get calendarView => 'Calendar view';

  @override
  String get language => 'Language';

  @override
  String get languageEs => 'Spanish';

  @override
  String get languageEn => 'English';

  @override
  String get languageCa => 'Catalan';

  @override
  String get binWidthGrouping => 'Grouping';

  @override
  String get yAxisMode => 'Y Axis:';

  @override
  String binWidthWarningFullscreen(
    int binWidth,
    int numGroups,
    int recommended,
  ) {
    return '💡 The current ${binWidth}mm grouping generates $numGroups groups. For better visualization, ${recommended}mm is recommended.';
  }

  @override
  String binWidthWarningExport(int binWidth, int numGroups, int recommended) {
    return '⚠️ The ${binWidth}mm grouping generates $numGroups groups. For sharing/exporting, ${recommended}mm is recommended.';
  }

  @override
  String yAxisWarningFullscreen(int step) {
    return 'ℹ️ Y-axis simplified in fullscreen mode to improve readability (steps of $step).';
  }

  @override
  String yAxisWarningNormal(int step) {
    return 'ℹ️ Y-axis auto-adjusted to maintain readability (steps of $step).';
  }

  @override
  String get numberOfFruits => 'No. of fruits';

  @override
  String get percentageOfFruits => '% of fruits';

  @override
  String get fruit => 'fruit';

  @override
  String get fruits => 'fruits';

  @override
  String get tapToSeeDetails => 'Tap to see details';

  @override
  String get exportFormat => 'Export Format';

  @override
  String get exportFormatJson => 'JSON (.fma)';

  @override
  String get exportFormatJsonDescription => 'Format for import';

  @override
  String get exportFormatCsv => 'CSV';

  @override
  String get exportFormatCsvDescription => 'Spreadsheet format';

  @override
  String get exportFormatTxt => 'TXT';

  @override
  String get exportFormatTxtDescription => 'Human-readable report';

  @override
  String get errorNoImageSelected => 'ERROR! No image selected';

  @override
  String get errorInvalidImageData => 'ERROR! Invalid image data';

  @override
  String get errorNoFruitsDetected => 'No fruits detected';

  @override
  String get errorSupportNotFound => 'Reference support not found';

  @override
  String get errorNoValidDetections => 'No valid detections found';

  @override
  String get errorNoValidPhotos => 'No valid photos were processed';

  @override
  String get errorMissingParams => 'Missing required parameters';

  @override
  String get errorGallerySavePermissionDenied =>
      'Could not save to gallery: Permission denied';

  @override
  String get errorGallerySaveFailed => 'Could not save to gallery';

  @override
  String get photoProcessed => 'photo processed successfully';

  @override
  String get photosProcessed => 'photos processed successfully';

  @override
  String get processingImages => 'Processing';

  @override
  String get ofTotal => 'of';

  @override
  String get noModel => 'No model';

  @override
  String get millimetersUnit => 'mm';

  @override
  String get errorImportWrongFileMeasurement =>
      'Wrong file: This is a MEASUREMENTS file (.measurement.fma). To import plots, use a .plot.fma file';

  @override
  String get errorImportWrongFilePlot =>
      'Wrong file: This is a PLOTS file (.plot.fma). To import measurements, use a .measurement.fma file';

  @override
  String get errorImportWrongFileGeneric =>
      'Wrong file format. Must be a .plot.fma or .measurement.fma file';

  @override
  String get errorImportWrongFileGenericMeasurements =>
      'Wrong file format. To import measurements, the file must have the .measurement.fma extension';

  @override
  String get errorImportWrongFileGenericPlots =>
      'Wrong file format. To import plots, the file must have the .plot.fma extension';

  @override
  String get errorImportEmptyFile => 'The file is empty';

  @override
  String get errorImportNoPlots => 'No plots found in the file';

  @override
  String get errorImportNoMeasurements => 'No measurements found in the file';

  @override
  String get errorImportParseError =>
      'Error reading the file. Check that the format is correct';

  @override
  String get errorImportParseErrorMeasurements =>
      'Error reading the file. The format must be a valid .measurement.fma file (JSON). Check that the file is not corrupted or modified';

  @override
  String get errorImportParseErrorPlots =>
      'Error reading the file. The format must be a valid .plot.fma file (JSON). Check that the file is not corrupted or modified';

  @override
  String get errorImportDialogTitle => 'Import Error';

  @override
  String get allPlotsAlreadyImported => 'All plots have already been imported';

  @override
  String get allMeasurementsAlreadyImported =>
      'All measurements have already been imported';

  @override
  String get importNoProcessedPlots => 'No plots were processed';

  @override
  String importSummaryOnlyNewPlots(Object measurements, num newPlots) {
    return 'Imported: $newPlots plots\nMeasurements: $measurements';
  }

  @override
  String importSummaryOnlyExistingNoChanges(num existingPlots) {
    return 'Reimported: $existingPlots plot\nNo changes in measurements';
  }

  @override
  String importSummaryOnlyExistingWithRestored(
    num existingPlots,
    Object restored,
  ) {
    return 'Reimported: $existingPlots plot\nRestored: $restored measurements';
  }

  @override
  String importSummaryOnlyExistingWithRestoredAndSkipped(
    num existingPlots,
    Object restored,
    Object skipped,
  ) {
    return 'Reimported: $existingPlots plot\nRestored: $restored | Skipped: $skipped';
  }

  @override
  String importSummaryMixedNoRestored(
    num existingPlots,
    Object newMeasurements,
    num newPlots,
  ) {
    return 'Imported: $newPlots new ($newMeasurements meas.)\nRe-imported: $existingPlots existing';
  }

  @override
  String importSummaryMixedWithRestored(
    num existingPlots,
    Object newMeasurements,
    num newPlots,
    Object restored,
    Object skipped,
  ) {
    return 'Imported: $newPlots new ($newMeasurements meas.)\nRe-imported: $existingPlots | Restored: $restored | Skipped: $skipped';
  }

  @override
  String importMeasurementsOnlyNew(num count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'measurements',
      one: 'measurement',
    );
    return 'Imported: $count $_temp0';
  }

  @override
  String importMeasurementsOnlyUpdated(num count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'measurements',
      one: 'measurement',
    );
    return 'Updated: $count $_temp0';
  }

  @override
  String importMeasurementsMixed(Object imported, Object updated) {
    return 'Imported: $imported\nUpdated: $updated';
  }

  @override
  String get noMeasurementsForThisPlot => 'No measurements found for this plot';

  @override
  String get viewAllPlotsOnMap => 'View all on map';

  @override
  String get noPlotsWithLocation => 'No plots with location';

  @override
  String histogramWarning1mmTooMany(Object count) {
    return 'Too many groups ($count). Use 3mm, 5mm or 10mm grouping.';
  }

  @override
  String histogramWarning3mmTooMany(Object count) {
    return 'Too many groups ($count) for 3mm. Use 5mm or 10mm.';
  }

  @override
  String histogramWarning5mmTooMany(Object count) {
    return 'Too many groups ($count) for 5mm. Use 10mm.';
  }

  @override
  String histogramInfo10mmMaxReached(Object count) {
    return 'Many groups ($count). You\'re already using the maximum grouping (10mm).';
  }

  @override
  String get deleteFromGalleryLabel => 'Delete from gallery';

  @override
  String get deleteFromGalleryDescription =>
      'This will permanently delete the selected images from your device.';

  @override
  String get imageNotAvailable => 'Image not available';

  @override
  String get imageNotAvailableDescription =>
      'The image is no longer available on this device. It may have been deleted from the gallery or processed from another device..';

  @override
  String get recoveringImageFromGallery =>
      'Attempting to recover image from gallery...';

  @override
  String get invertedAxesMessage => 'Inverted axes to facilitate visualization';

  @override
  String get exportCalendar => 'Export to Google Calendar';

  @override
  String get exportCalendarSuccess => 'Calendar exported successfully';

  @override
  String get exportCalendarError => 'Error exporting calendar';

  @override
  String get exportCalendarNoMeasurements => 'No measurements to export';

  @override
  String get exportToGoogleCalendar => 'Export to Google Calendar';

  @override
  String get shareWithOtherApps => 'Share with other apps';

  @override
  String get appTitle => 'Fruit Measure App';

  @override
  String get errorUnknown => 'Unknown error';

  @override
  String get exportMeasurementsCsvHeader =>
      'Measurement ID,Measurement Name,Model,Measurement Creation Date,Photo ID,Photo Creation Date,Photo Capture Date,Latitude,Longitude,Detection ID,Caliber (mm),Confidence,Class';

  @override
  String get exportReportTitle => 'MEASUREMENTS EXPORT REPORT';

  @override
  String get exportReportSeparator =>
      '========================================';

  @override
  String get exportDateLabel => 'Export Date:';

  @override
  String get exportTotalMeasurementsLabel => 'Total Measurements:';

  @override
  String get exportMeasurementLabel => 'MEASUREMENT:';

  @override
  String get exportUnnamedLabel => 'Unnamed';

  @override
  String get exportIdLabel => '  ID:';

  @override
  String get exportModelLabel => '  Model:';

  @override
  String get exportNotAvailableLabel => 'N/A';

  @override
  String get exportCreationDateLabel => '  Creation Date:';

  @override
  String get exportObservationsLabel => '  Observations:';

  @override
  String get exportNoneLabel => 'None';

  @override
  String get exportTotalPhotosLabel => '  Total Photos:';

  @override
  String get exportPhotoLabel => '  PHOTO';

  @override
  String get exportCaptureDataLabel => '    Capture Date:';

  @override
  String get exportLocationLabel => '    Location:';

  @override
  String get exportDetectionsLabel => '    Detections:';

  @override
  String get exportDetectionLabel => '      DETECTION';

  @override
  String get exportCaliberLabel => '        Caliber:';

  @override
  String get exportConfidenceLabel => '        Confidence:';

  @override
  String get exportClassLabel => '        Class:';

  @override
  String get exportPlotsCsvHeader =>
      'Plot ID,Plot Name,Variety,Farmer,Measurement ID,Measurement Name,Model,Measurement Creation Date,Photo ID,Photo Creation Date,Photo Capture Date,Latitude,Longitude,Detection ID,Caliber (mm),Confidence,Class';

  @override
  String get exportPlotsReportTitle => 'PLOTS EXPORT REPORT';

  @override
  String get exportTotalPlotsLabel => 'Total Plots:';

  @override
  String get exportPlotLabel => 'PLOT:';

  @override
  String get exportVarietyLabel => '  Variety:';

  @override
  String get exportFarmerLabel => '  Farmer:';

  @override
  String get calendarEventMeasurementPrefix => 'Measurement -';

  @override
  String get calendarEventObservations => 'Observations:';

  @override
  String get calendarEventModel => 'Model:';

  @override
  String get calendarEventPlot => 'Plot:';

  @override
  String get calendarEventVariety => 'Variety:';

  @override
  String get errorFileWriteFailed => 'Error writing file';

  @override
  String get errorFileReadFailed => 'Error reading file';

  @override
  String get errorExportFailed => 'Error exporting';

  @override
  String get errorImportUserFailed => 'Error importing user';

  @override
  String get errorDeletePhotoFailed => 'Error deleting photo';

  @override
  String get errorYoloPredictionFailed => 'Error in fruit detection';

  @override
  String get errorUnexpected => 'Unexpected error';

  @override
  String get tooltipViewFullscreen => 'View fullscreen';

  @override
  String get tooltipScrollMode => 'Scroll mode';

  @override
  String get tooltipFullView => 'Full view';

  @override
  String get tooltipViewPreviousValues => 'View previous values';

  @override
  String get tooltipViewNextValues => 'View next values';

  @override
  String get tooltipRotateScreen => 'Rotate screen';

  @override
  String get modelNameFruto => 'Fruit';

  @override
  String get modelNameCorimbo => 'Cluster';

  @override
  String get modelNameCaixa => 'Box';

  @override
  String get noCalibersDetected => 'No calibers detected';

  @override
  String get unknown => 'Unknown';

  @override
  String get confidenceThresholdLabel => 'Confidence level';

  @override
  String get confidenceThresholdDescription =>
      'Minimum threshold for detections';

  @override
  String get yoloLicenseTitle => 'YOLO License';

  @override
  String get yoloLicenseText =>
      'This application incorporates components of Ultralytics YOLOv11.\n\nYOLOv11 © Ultralytics and contributors.\nLicensed under the GNU Affero General Public License v3.0 (AGPL-3.0).\n\nThis application is distributed without any warranty.\n\nSource code available at:\nhttps://github.com/GRAP-UdL-AT/FruitMeasureApp';
}
