// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fruit_measure_app/domains/measurements/models/model_enum.dart';
import 'package:fruit_measure_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DetectionAdapter());
    registerAdapter(MeasurementAdapter());
    registerAdapter(ModelAdapter());
    registerAdapter(PhotoAdapter());
    registerAdapter(PlotAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DetectionAdapter());
    registerAdapter(MeasurementAdapter());
    registerAdapter(ModelAdapter());
    registerAdapter(PhotoAdapter());
    registerAdapter(PlotAdapter());
    registerAdapter(UserAdapter());
  }
}
